/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-03 08:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajaxTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>AJAX 테스트 페이지</h1>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<button id=\"ajaxTest1\">Ajax Test 1</button>\r\n");
      out.write("	<button id=\"ajaxTest2\">Ajax Test 2</button>\r\n");
      out.write("	<button id=\"ajaxTest3\">Ajax Test 3</button>\r\n");
      out.write("	<button id=\"ajaxTest4\">Ajax Test 4</button>\r\n");
      out.write("	<button id=\"ajaxTest5\">Ajax Test 5</button>\r\n");
      out.write("	<button id=\"ajaxTest6\">Ajax Test 6</button>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(\"#ajaxTest1\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest1.kh',\r\n");
      out.write("			data : {str : '스프링', num : 10},\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				console.log(res);\r\n");
      out.write("			}\r\n");
      out.write("			,error : function(){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#ajaxTest2\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest2.kh',\r\n");
      out.write("			data : {str : '스프링', num : 10},\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				console.log(res)\r\n");
      out.write("			}\r\n");
      out.write("			,error : function (){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#ajaxTest3\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest3.kh',\r\n");
      out.write("			data : {str : '스프링', num : 10},\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				//Controller에서 JSONArray에 요소들을 추가하고, 응답하면 응답된 데이터 자료형이 string임.\r\n");
      out.write("				console.log(typeof res);\r\n");
      out.write("				\r\n");
      out.write("				console.log(res);\r\n");
      out.write("				res = JSON.parse(res); //JSON.parse : JSON 형식의 \"문자열\"을 JSON으로 변환해주는 메소드\r\n");
      out.write("				\r\n");
      out.write("				//parse 메소드를 통해, Javascript Object로 변환하여 배열이 출력됨.\r\n");
      out.write("				console.log(res);\r\n");
      out.write("				console.log(typeof res);\r\n");
      out.write("			}\r\n");
      out.write("			,error : function (){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#ajaxTest4\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest4.kh',\r\n");
      out.write("			data : {str : '스프링', num : 10},\r\n");
      out.write("			//dataType : 'json',  //응답 데이터 형식을 json으로 지정(Controller에서 json 문자열로 응답 시 자동으로 JSON 오브젝트로 변환)\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				console.log(res)\r\n");
      out.write("			    console.log(typeof res);\r\n");
      out.write("				\r\n");
      out.write("				res = JSON.stringify(res);\r\n");
      out.write("				console.log(typeof res);\r\n");
      out.write("			}\r\n");
      out.write("			,error : function (){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	$(\"#ajaxTest5\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest5.kh',\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				console.log(res);\r\n");
      out.write("				console.log(typeof res);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			,error : function (){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#ajaxTest6\").on('click', function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/ajax/ajaxTest6.kh',\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			success : function(res){\r\n");
      out.write("				console.log(res);\r\n");
      out.write("				console.log(typeof res);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			,error : function (){\r\n");
      out.write("				console.log('ajax 통신 오류 !');\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
